database:
  host: "localhost"
  port: 3306
  user: "root"
  pass: ""
  dbName: "game_practice"
setup:
  spawn-location: 256.5|63.0|250.5|world|-358.5637|15.373675
  editor-location: 304.5|60.0|250.5|world|-90.70831|1.133154
tab:
  enabled: true
  strings:
    '1': ''
    '2': ''
    '3': '§6Your Ratings'
    '4': '§bDebuff:'
    '5': '§7%Debuff_rating%'
    '6': '§bNoDebuff:'
    '7': '§7%NoDebuff_rating%'
    '8': '§bVanilla:'
    '9': '§7%Vanilla_rating%'
    '10': '§bCombo:'
    '11': '§7%Combo_rating%'
    '12': '§bSoup:'
    '13': '§7%Soup_rating%'
    '14': '§bArcher:'
    '15': '§7%Archer_rating%'
    '16': '§bGApple:'
    '17': '§7%GApple_rating%'
    '18': ''
    '19': '§bStore:'
    '20': '§7store.pvptemple.it'
    '21': '  §6§lPvPTemple'
    '22': ''
    '23': '§6Online Players:'
    '24': '§7%online_players%'
    '25': ''
    '26': '§6Fighting:'
    '27': '§7%playing_amount%'
    '28': ''
    '29': '§6Queuing:'
    '30': '§7%queuing_amount%'
    '31': ''
    '32': '§6Latency:'
    '33': '§7%player_ping%'
    '34': ''
    '35': ''
    '36': ''
    '37': ''
    '38': ''
    '39': ''
    '40': ''
    '41': ''
    '42': ''
    '43': '§6Statistics:'
    '44': '§bGlobal Rating:'
    '45': '§7%globalrating%'
    '46': '§bRanked Wins:'
    '47': '§7%ranked_wins%'
    '48': '§bRanked Losses:'
    '49': '§7%ranked_losses%'
    '50': '§bUnranked Wins:'
    '51': '§7%unranked_wins%'
    '52': '§bUnranked Losses:'
    '53': '§7%unranked_losses%'
    '54': '§bMatches Played:'
    '55': '§7%matches_played%'
    '56': ''
    '57': ''
    '58': ''
    '59': '§bTeamSpeak:'
    '60': '§7ts.pvptemple.it:1919'